version: '3.9'

services:
  #  172.19.0.3
  flask_server:
    container_name: flask_server
    build: ./flask_module/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    command: python app.py

  # 172.19.0.2
  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
        interval: 10s
        retries: 5
        start_period: 10s
        timeout: 10s
